SIMPLYPRINT_URL = "https://simplyprint.io/"
UPDATE_URL = "https://request.simplyprint.io"
API_VERSION = "0.0.3"
WEBCAM_SNAPSHOT_URL = SIMPLYPRINT_URL + "api/receive_snapshot.php"
SIMPLYPRINT_PLUGIN_INSTALL_URL = "https://github.com/SimplyPrint/OctoPrint-SimplyPrint/archive/master.zip"
